---
title: "Pay Ratio"
output: pdf_document
---

```{r Packages, include=FALSE, message=F, warning=F, echo=F}
library(edgar)
library(tidyverse)
library(cluster)
library(openxlsx)
setwd("~/Dr. Athavale/Pay Ratio")
```

```{r Functions}
# This function Extracts the CEO Pay Ratio paragraph from the proxy statement
parser <- function(proxy) {
   # Creating a dictionary of phrases to search
  dict <- c("PAY RATIO",
            "Pay Ratio",
            "CEO Pay Ratio",
            "CEO Pay-Ratio",
            "\\d{4} Pay Ratio")
  
  for (j in 1:length(dict)) {
    if (str_detect(proxy, regex(dict[j], ignore_case = T))) {
      positions <-
        as.data.frame(str_locate_all(proxy, regex(dict[j], ignore_case = T)))
      break
    } else {
      positions <- NA
    }
  }
  if (!is.na(positions)) {
    if (positions[1, 1] > 250000) {
      paragraph <- str_sub(proxy,
                           start = positions[1, 1],
                           end = (positions[1, 1] + 35000))
    } else if (positions[2, 1] > 350000 &
               positions[nrow(positions), 1] > 500000) {
      paragraph <- str_sub(proxy, 
                           start = positions[2, 1], 
                           end = positions[2, 1] + 35000)
    } else if (positions[3, 1] > 450000 &
               positions[nrow(positions), 1] > 500000) {
      paragraph <- str_sub(proxy, 
                           start = positions[3, 1], 
                           end = positions[3, 1] + 35000)
    } else if (positions[nrow(positions), 1] < 45000) {
      paragraph <- "too short"
    }
  } else if (is.na(positions)) {
    paragraph <- NA
  } else {
    paragraph <- "too short"
  }
  return(paragraph)
}

# This function extracts the ratio from the paragraph
ratio.extractor <- function(vec) {
  # Creating a list of formats
  form <- c(
    "\\d\\,\\d+:1",
    "\\d+\\.\\d+:1",
    "\\d+\\.\\d+ to 1",
    "\\d+:1",
    "\\d+-to-1",
    "\\d+ to 1",
    "\\d+ to&nbsp;1",
    "[0-9]+ to 1",
    "\\d+\\s(to)\\s1",
    "[1-9]+\\s(to)\\s1",
    "\\d+\\s(times)",
    "1-(to)-\\d+",
    "[1-9]+\\.\\d+\\s(to)\\s1",
    "\\([1-9]{1,3}\\)\\s(times)",
    "1 to \\d+",
    "1:\\d+",
    "1:\\d+.\\d+",
    "\\d+;to 1",
    "\\d+</font><font style=\"font-family:inherit;font-size:10pt;\">:1"
  )
  
  if (!is.na(vec)) {
    for (j in 1:length(form)) {
      if (str_detect(vec, form[j])) {
        info <- str_extract(vec, form[j])
        break
      }
      else
        info <- "didn't extract"
    }
  } else {
    info <- NA
  }
  return(info)
}

# This function extracts CEO compensation from the paragraph
comp.extractor <- function(vec) {
  ceo_comp_forms <- c(
    '\\$[0-9]{2}(,)[0-9]{3}(,)[0-9]{3}',
    '\\$[0-9]{1}(,)[0-9]{3}(,)[0-9]{3}',
    '[0-9]{2}(,)[0-9]{3}(,)[0-9]{3}',
    '[0-9]{1}(,)[0-9]{3}(,)[0-9]{3}',
    '\\$[0-9]{3}(,)[0-9]{3}',
    '[0-9]{3}(,)[0-9]+'
  )
  
  median_comp_forms <- c('\\$[0-9]{3}(,)[0-9]{3}',
                         '\\$[0-9]{2}(,)[0-9]{3}')
  
  ceo_positions <- data.frame()
  before <- NA
  after <- NA
  median_comp <- NA
  
  if (!is.na(vec)) {
    for (j in 1:length(ceo_comp_forms)) {
      if (str_detect(vec, ceo_comp_forms[j])) {
        ceo_comp <- str_extract(vec, ceo_comp_forms[j])
        ceo_positions <- str_locate(vec, ceo_comp_forms[j])
        break
      } else {
        ceo_comp <- NA
      }
    }
    
    if (!is.na(ceo_comp)) {
      before <- str_sub(vec, start = 0, end = ceo_positions[1, 1])
      after <-
        str_sub(vec, start = ceo_positions[1, 2], end = ceo_positions[1, 2] + 1500)
    }
    
    if (!is.na(before)) {
      for (k in 1:length(median_comp_forms)) {
        if (str_detect(before, median_comp_forms[k])) {
          median_comp <- str_extract(before, median_comp_forms[k])
          break
        } else if (str_detect(after, median_comp_forms[k])) {
          median_comp <- str_extract(after, median_comp_forms[k])
          break
        } else {
          median_comp <- NA
        }
      }
    }
  } else {
    ceo_comp <- NA
    median_comp <- NA
  }
  return(c(ceo_comp, median_comp))
}

```


```{r Formatting for Extraction}
# Loading Filings
## Listing Directories
dirs <- list.dirs('~/Dr. Athavale/Pay Ratio/Data/Edgar filings_HTML view/Form DEF 14A')

dirs <- dirs[-1]

## Listing directory contents
files <- rep(NA, length(dirs))
for (i in 1:length(dirs)) {
  num_files <- length(dir(dirs[i]))
  contents <- dir(dirs[i])
  if (num_files == 1) {
    files[i] <- contents
  } else {
    files[i] <- contents[num_files]
  }
}

## Listing CIK numbers
file_names <- list.files('~/Dr. Athavale/Pay Ratio/Data/Edgar filings_HTML view/Form DEF 14A')
```


```{r Extracting Paragraphs, message=F, warning=F}
## Paragraphing Loop
paragraph <- rep(NA, length(files))

for (i in 1:length(files)) {
  proxy <- paste(readLines(paste('~/Dr. Athavale/Pay Ratio/Data/Edgar filings_HTML view/Form DEF 14A/', file_names[i], '/', files[i], sep = "")), collapse = '\n')
  paragraph[i] <- parser(proxy)
}
```


```{r Extracting Ratios and Compensation}
# Result data structures
ratios <- rep(NA, length(paragraph))
ciks <- str_extract(files, "\\d+")

# Ratio and Compensation Extraction
ratios <- lapply(paragraph, ratio.extractor)
comp_df <- data.frame()

for(i in 1:length(paragraph)){
  comp_vec <- comp.extractor(paragraph[i])
  comp_df[i, 1] <- str_trim(comp_vec[1])
  comp_df[i, 2] <- str_trim(comp_vec[2])
}

# Data formatting
flat_cik <- as.numeric(unlist(ciks))
flat_ratios <- str_trim(as.character(unlist(ratios)))

compiled_df <- as.data.frame(cbind(flat_cik, flat_ratios, comp_df))

clean_df <- compiled_df %>%
  mutate(ratio = ifelse(flat_ratios == "didn't extract", 
                        "didn't extract", 
                        str_extract(flat_ratios, "\\d{2,3}"))) %>%
  rename(cik = flat_cik, ceo = V1, median = V2) %>%
  select(cik, ceo, median, ratio) %>%
  mutate(ceo = str_trim(gsub('[$]','', ceo)),
         median = str_trim(gsub('[$]','', median)),
         ratio = ifelse(ratio == "didn't extract", NA, ratio)) %>%
  mutate(ceo = as.numeric(gsub(",","",ceo)),
         median = as.numeric(gsub(",","",median)),
         ratio = as.numeric(gsub(",","",ratio)))

```


```{r Data Validation}
check_df <- clean_df %>%
  filter(!is.na(ceo) & !is.na(ratio) & !is.na(median)) %>%
  filter(ceo != 7226785 & median != 71304) %>%
  mutate(check = abs(ratio - (ceo/median))) %>%
  filter(check < 1)

check_df %>%
  summarize(n())

validation <- check_df %>%
  filter(cik == 908255 | cik == 1370880 | cik == 750556 | cik == 1097864 | cik == 1596783 | cik == 1584509 | cik == 7536 | cik == 1609702 | cik == 108312 | cik == 74260)

cv <- pf(0.05, 1, 1, lower.tail = F)

#new_validation <- check_df %>%
#  anti_join(validation) %>%
#  sample_n(10)

```


```{r Data Export}
sheets <- list("Data" = check_df, "Validation" = validation, "New Validation" = new_validation)
write.csv(check_df, "~/Dr. Athavale/Pay Ratio/Data/2018 Pay Ratio Data.csv")
write.xlsx(sheets, "~/Dr. Athavale/Pay Ratio/Data/2018 Pay Ratio Data.xlsx")
```


```{r Lost Data}
proxy_count <- length(paragraph)

no_ratio <- clean_df %>%
  filter(is.na(ratio)) %>%
  summarize(n())

no_median <- clean_df %>%
  filter(is.na(median)) %>%
  summarize(n())

no_ceo <- clean_df %>%
  filter(is.na(ceo)) %>%
  summarize(n())

no_na <- clean_df %>%
  filter(is.na(median) | is.na(ceo) | is.na(ratio)) %>%
  summarize(n())

check_loss <- clean_df %>%
  filter(!is.na(ceo) & !is.na(ratio) & !is.na(median)) %>%
  filter(ceo != 7226785 & median != 71304) %>%
  mutate(check = abs(ratio - (ceo/median))) %>%
  filter(check > 1) %>%
  summarize(n())

clean_df %>%
  filter(is.na(ratio) & !is.na(ceo))
```
